i-Cell-Mobilsoft-Open-Source/coffee

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/ApplicationConfiguration.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/CompositeCacheLoaderKey.java
fix NPE on ApplicationConfiguration in massive multi thread applic
> Closes #11 fix NPE on ApplicationConfiguration

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/ApplicationConfiguration.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/CompositeCacheLoaderKey.java
fix NPE on ApplicationConfiguration in massive multi thread application
> Fixes #10 NPE on ApplicationConfiguration

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/ApplicationConfiguration.java
- fix memory leak, weakeys use == instead of equals, every new key will be stored
- if etcd fail to respon or the key is missing, the local cache will store empty for 30 minutes
- ICDEV-8824 etcd cache optimalizáció
> App config cache optimization

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/utils/ResponseUtil.java
- Fájl név javítása, idéző jelek között kell visszaadni.
> #34 fájl neve nem jó letöltéskor

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/utils/ResponseUtil.java
- Fix #38 : Felesleges szóköz kiszedése
> #38 Felesleges szóköz kiszedése fájlnévből

- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/config/IConfigKey.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/service/BaseEtcdService.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/string/StringHelper.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/string/StringUtil.java
- docs/common/core/coffee-rest.adoc
- docs/common/module/coffee-module-etcd.adoc
- docs/migration/migration101to110.adoc
> #28 StringHelper.maskValueInXmlJson nagy Stringnel belassul

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultGeneralExceptionMapper.java
- docs/migration/migration100to110.adoc
- docs/migration/migration101to110.adoc
> #37 default general exception mapper enhancements

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/json/JsonMessageBodyReaderBase.java
- docs/migration/migration110to120.adoc
> #69 changed private methods of JsonMessageBodyReaderBase to protected

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/service/BaseService.java
- docs/migration/migration110to120.adoc
> #78 changed BaseService log and error handling functions to protected

- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultLoggerClientResponseFilter.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/log/RequestResponseLogger.java
- docs/migration/migration110to120.adoc
Ugyan az, mint a #96, csak az 1.2.x-es branch-re.
> #93 DefaultLoggerClientResponseFilter#logEntity NPE fix

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/common/RedisStreamHandler.java
- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/common/RedisStreamPublication.java
- docs/common/module/coffee-module-redisstream.adoc
> #118 Redis stream producer egyszerre több üzenetet is tudjon kiküldeni 

- coffee-dto/coffee-dto-base/src/main/resources/META-INF/beans.xml
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/FaultTypeParser.java
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/FaultTypeParserExtension.java
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- docs/common/module/coffee-module-mp-restclient.adoc
- docs/migration/migration120to130.adoc
> #119 Create FaultTypeParserExtension

- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/repository/RedisRepository.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/service/AbstractRedisService.java
- docs/common/module/coffee-module-redis.adoc
- docs/migration/migration120to130.adoc
hscan paraméterezés count értékkel
> #128 Redis hscan paraméterezés

- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/DurationConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/JsonUtil.java
- coffee-tool/src/test/java/hu/icellmobilsoft/coffee/tool/gson/JsonUtilTest.java
- docs/common/core/coffee-rest.adoc
- docs/migration/migration140to150.adoc
> Json Duration handling

- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/producer/DefaultEtcdConfigSource.java
- docs/migration/migration140to150.adoc
> #162 WildFly 23 kompatilibitás

- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/date/DateUtil.java
- coffee-tool/src/test/java/hu/icellmobilsoft/coffee/tool/utils/date/DateUtilTest.java
- docs/migration/migration140to150.adoc
#161 
Egy projectből átemelve, kiegészítve tesztekkel
> Dateutil bovites

- coffee-module/coffee-module-ruleng/src/main/java/hu/icellmobilsoft/coffee/module/ruleng/evaluator/AbstractEvaluator.java
- docs/migration/migration160to170.adoc
> #194 AbstractEvaluator dispose atalakitas

- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/manager/RedisManager.java
> #199 null jedis field after connection close

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
- docs/migration/migration170to180.adoc
> #164 BatchService verzió kezelés

- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/AbstractEntity.java
- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/AbstractIdentifiedAuditEntity.java
- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/IIdentifiedAuditEntity.java
- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/IVersionable.java
- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/generator/EntityIdGenerator.java
- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/javatime/AbstractIdentifiedAuditEntity.java
- docs/migration/migration170to180.adoc
> #209 Interface bevezetése AbstractEntityk-re

- coffee-dto/coffee-dto-base/src/main/java/hu/icellmobilsoft/coffee/dto/url/BaseServicePath.java
- coffee-module/coffee-module-activemq/src/main/java/hu/icellmobilsoft/coffee/module/activemq/producer/AbstractJmsClient.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/service/BaseEtcdService.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/service/AbstractRedisService.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/ApplicationConfiguration.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/configuration/ConfigurationHelper.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/utils/XsdResourceResolver.java
- coffee-se/coffee-se-logging/src/main/java/hu/icellmobilsoft/coffee/se/logging/mdc/Slf4jMDCAdapter.java
- docs/migration/migration170to180.adoc
> #218 Log optimalizáció

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/consumer/RedisStreamConsumerExecutor.java
- docs/migration/migration170to180.adoc
> #222 RedisStreamConsumerExecutor#startLoop Throwable kezelés

- coffee-dto/coffee-dto-xsd/src/main/resources/xsd/hu/icellmobilsoft/coffee/dto/common/common.xsd
- coffee-dto/coffee-dto-xsd/src/main/resources/xsd/hu/icellmobilsoft/coffee/dto/common/commonservice.xsd
- docs/migration/migration170to180.adoc
> #226 commonservice.xsd - context, requestId modositasa

- coffee-bom/pom.xml
- coffee-dto/coffee-dto-gen/pom.xml
- coffee-module/coffee-module-mongodb/pom.xml
- coffee-module/coffee-module-mp/pom.xml
- coffee-module/coffee-module-totp/pom.xml
- docs/migration/migration170to180.adoc
Szükségesek a verzióemelések a Roaster-es task miatt
https://github.com/i-Cell-Mobilsoft-Open-Source/roaster/pull/51
> roaster #40 microprofile verzió emelése 4.x-re

- coffee-module/coffee-module-mongodb/src/main/java/hu/icellmobilsoft/coffee/module/mongodb/extension/MongoConfigHelper.java
- coffee-module/coffee-module-mongodb/src/main/java/hu/icellmobilsoft/coffee/module/mongodb/extension/MongoDbClientFactory.java
- docs/common/module/coffee-module-mongodb.adoc
- docs/migration/migration170to180.adoc
> #228 MongoDbClient-nek ne legyen RequestScope-ú függősége

- coffee-module/coffee-module-etcd/pom.xml
- docs/migration/migration170to180.adoc
jetcd-core verzió frissítés <version>0.5.0</version> -> <version>0.6.1</version>
> #229 jetcd-core upgrade

- coffee-model/coffee-model-base/pom.xml
> #250 coffee-model-base javadoc-plugin függőség kiszedése

- coffee-module/coffee-module-configdoc/src/main/java/hu/icellmobilsoft/coffee/module/configdoc/ConfigDoc.java
- coffee-module/coffee-module-configdoc/src/main/java/hu/icellmobilsoft/coffee/module/configdoc/config/ConfigDocConfig.java
- coffee-module/coffee-module-configdoc/src/main/java/hu/icellmobilsoft/coffee/module/configdoc/processor/ConfigDocProcessor.java
- coffee-module/coffee-module-configdoc/src/test/java/hu/icellmobilsoft/coffee/module/configdoc/ConfigDocTest.java
- docs/common/module/coffee-module-configdoc.adoc
- docs/migration/migration180to190.adoc
> #253 @ConfigDoc konfiguráció

- coffee-module/coffee-module-redis/pom.xml
- docs/migration/migration190to1100.adoc
> #279 Jedis 4.2.3 upgrade

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/service/RedisStreamService.java
- docs/migration/migration1100to1110.adoc
> #293 RedisStreamConsumerExecutor redis connection korán záródik le - fix

- coffee-cdi/pom.xml
- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/logger/LogProducer.java
- coffee-module/coffee-module-localization/pom.xml
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultLoggerClientRequestFilter.java
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/provider/DefaultLoggerClientResponseFilter.java
- docs/migration/migration1100to1110.adoc
deltaspike fuggoseg megszuntetese
> #302 cdi modul deprecate deltaspike

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/publisher/RedisStreamPublisher.java
- docs/migration/migration1100to1110.adoc
> #306 RedisStreamPublisher nem veszi figyelembe a producer config-ot - fix

- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/logger/LogProducer.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/util/JpaUtil.java
- coffee-module/coffee-module-activemq/src/main/java/hu/icellmobilsoft/coffee/module/activemq/util/JmsUtil.java
- coffee-module/coffee-module-mongodb/src/main/java/hu/icellmobilsoft/coffee/module/mongodb/extension/MongoExtension.java
- coffee-module/coffee-module-mongodb/src/main/java/hu/icellmobilsoft/coffee/module/mongodb/producer/MongoFactory.java
- coffee-module/coffee-module-mongodb/src/main/java/hu/icellmobilsoft/coffee/module/mongodb/util/MongoJsonUtil.java
- coffee-module/coffee-module-mp/coffee-module-mp-restclient/src/main/java/hu/icellmobilsoft/coffee/module/mp/restclient/exception/FaultTypeParser.java
- coffee-module/coffee-module-totp/src/test/java/hu/icellmobilsoft/coffee/module/otp/TOtpTest.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/apache/BaseApacheHttpClient.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/utils/RequestUtil.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/error/XsdValidationErrorCollector.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/reader/XmlRequestVersionReader.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/utils/XsdResourceResolver.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/DateConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/JsonUtil.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/LocalDateConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/OffsetDateTimeConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/OffsetTimeConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/gson/XMLGregorianCalendarConverter.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/properties/PropertyReader.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/date/DateUtil.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/marshalling/MarshallingUtil.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/string/EncodeUtil.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/string/RandomUtil.java
- docs/migration/migration1100to1110.adoc
Deprecated metódusok megszüntetve
> #304 LogProducer depraceted-ek kiszedése

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/config/IStreamGroupConfig.java
- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/config/StreamGroupConfig.java
- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/consumer/RedisStreamConsumerExecutor.java
- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/service/RedisStreamService.java
- docs/common/module/coffee-module-redisstream.adoc
- docs/migration/migration1110to1120.adoc
> #319 Redis stream NOACK

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
- docs/migration/migration1120to1130.adoc
- null értékű objektumok beállítása Types.NULL-ként
- Types.BOOLEAN ág lekezelése
- migrációs dokumentáció bővítése
> #334 - BatchService Boolean mentés probléma

- coffee-bom/pom.xml
- coffee-rest/pom.xml
- docs/migration/migration1120to1130.adoc
> #260 - resteasy upgrade 3.6.2.Final -> 4.7.6.Final

- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/producer/DefaultEtcdConfigSource.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/producer/DefaultEtcdFactory.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/service/EtcdService.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/util/EtcdClientBuilderUtil.java
- docs/migration/migration1120to1130.adoc
> #299 - Handle response waiting timeout.

- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/config/IConfigKey.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/cdi/BaseApplicationContainer.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultExceptionMessageTranslator.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/exception/DefaultGeneralExceptionMapper.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/projectstage/ProjectStage.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/projectstage/ProjectStageEnum.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/projectstage/ProjectStageProducer.java
- coffee-rest/src/test/java/hu/icellmobilsoft/coffee/rest/projectstage/ProjectStageProducerTest.java
- coffee-rest/src/test/resources/META-INF/beans.xml
- docs/common/core/coffee-rest.adoc
- docs/migration/migration1120to1130.adoc
> #57 - org.apache.deltaspike.ProjectStage leváltása mp-config megoldásra (coffee v2-be)

- coffee-deltaspike/coffee-deltaspike-message/src/main/java/org/apache/deltaspike/core/impl/message/DefaultMessageResolver.java
- docs/migration/migrationTo2_0_0.adoc
ConcurrentModificationException fix
> #381 deltaspike ConcurrentModificationException

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/annotation/Transactional.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/helper/TransactionHelper.java
- docs/migration/migrationTo2_0_0.adoc
> #391 - Create Customized jakarta Transactional annotation and use in TransactionHelper

- coffee-deltaspike/coffee-deltaspike-message/src/test/java/org/apache/deltaspike/core/impl/message/DefaultMessageContextTest.java
- coffee-module/coffee-module-csv/src/main/java/hu/icellmobilsoft/coffee/module/csv/CsvUtil.java
- coffee-module/coffee-module-csv/src/test/java/hu/icellmobilsoft/coffee/module/csv/CsvUtilTest.java
- docs/migration/migrationTo2_0_0.adoc
- CsvUtil ICSVWriter.DEFAULT_LINE_END -> System.lineSeparator()
- CsvUtilTest windowson letiltott teszt aktiválása
- DefaultMessageContextTest magyar default locale javítás
> #372 - CsvUtil windows platform fix

- docs/migration/migrationTo2_0_0.adoc
- pom.xml
> #365 - Jandex bekötése

- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/service/EtcdService.java
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/util/EtcdClientBuilderUtil.java
- docs/migration/migrationTo2_0_0.adoc
> #418 etcd random timeout fix

- coffee-bom/pom.xml
- coffee-module/coffee-module-etcd/pom.xml
- docs/migration.adoc
- docs/migration/migration200to210.adoc
> #435 ETCD driver update + GRPC transitive dependency definition V2

- coffee-bom/pom.xml
- coffee-dto/coffee-dto-stub-gen/pom.xml
- coffee-dto/coffee-dto-xsd2proto/pom.xml
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/hu/icellmobilsoft/coffee/dto/common/common/hu_icellmobilsoft_coffee_dto_common_common.proto
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/hu/icellmobilsoft/coffee/dto/common/commonsecurity/hu_icellmobilsoft_coffee_dto_common_commonsecurity.proto
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/hu/icellmobilsoft/coffee/dto/common/commonservice/hu_icellmobilsoft_coffee_dto_common_commonservice.proto
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/hu/icellmobilsoft/coffee/dto/document/document/hu_icellmobilsoft_coffee_dto_document_document.proto
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/hu/icellmobilsoft/coffee/dto/notification/notification/hu_icellmobilsoft_coffee_dto_notification_notification.proto
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/schema2proto/config.yaml
- coffee-dto/coffee-dto-xsd2proto/src/main/resources/xsd/hu/icellmobilsoft/coffee/dto/proto/super-proto.xml
- coffee-dto/pom.xml
- coffee-grpc/coffee-grpc-api/pom.xml
- coffee-grpc/coffee-grpc-api/src/main/java/hu/icellmobilsoft/coffee/grpc/api/service/IGrpcService.java
- coffee-grpc/coffee-grpc-base/pom.xml
- coffee-grpc/coffee-grpc-base/src/main/java/hu/icellmobilsoft/coffee/grpc/base/exception/ExceptionHandler.java
- coffee-grpc/coffee-grpc-base/src/main/java/hu/icellmobilsoft/coffee/grpc/base/exception/ExceptionMapper.java
- coffee-grpc/coffee-grpc-base/src/main/java/hu/icellmobilsoft/coffee/grpc/base/exception/GrpcRuntimeExceptionWrapper.java
- coffee-grpc/coffee-grpc-base/src/main/java/hu/icellmobilsoft/coffee/grpc/base/exception/StatusResponse.java
- coffee-grpc/coffee-grpc-protoc/pom.xml
- coffee-grpc/coffee-grpc-protoc/src/main/java/hu/icellmobilsoft/coffee/grpc/protoc/plugin/CoffeeGrpcGenerator.java
- coffee-grpc/coffee-grpc-protoc/src/main/resources/ServiceImpl.mustache
- coffee-grpc/coffee-grpc-protoc/src/main/resources/ServiceInterface.mustache
- coffee-grpc/pom.xml
- docs/common/coffee-core.adoc
- docs/common/core/coffee-grpc.adoc
- docs/migration/migration200to210.adoc
- pom.xml
> #438 GRPC objects generating support V2

- coffee-bom/pom.xml
- coffee-grpc/coffee-grpc-client-extension/pom.xml
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/GrpcClient.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/config/GrpcClientConfig.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/config/GrpcClientConfigProducer.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/config/IGrpcClientConfig.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/extension/GrpcClientExtension.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/extension/GrpcClientProducerFactory.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/extension/GrpcDelegatingBeanAttributes.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/extension/ManagedChannelProducer.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/interceptor/ClientRequestInterceptor.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/interceptor/ClientResponseInterceptor.java
- coffee-grpc/coffee-grpc-client-extension/src/main/resources/META-INF/beans.xml
- coffee-grpc/coffee-grpc-client-extension/src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension
- coffee-grpc/pom.xml
- docs/hu/common/core/coffee-grpc.adoc
- docs/hu/migration/migration200to210.adoc
#455 GRPC client extension modul V2
> #455 GRPC client extension modul V2

- coffee-bom/pom.xml
- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/trace/constants/Tags.java
- coffee-grpc/coffee-grpc-client-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/client/extension/ManagedChannelProducer.java
- coffee-grpc/coffee-grpc-opentracing-impl/pom.xml
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/client/OpenTraceClientCall.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/client/OpenTraceClientCallListener.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/client/OpenTraceClientInterceptor.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/common/AbstractOpenTraceInterceptor.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/server/OpenTraceServerCall.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/server/OpenTraceServerCallListener.java
- coffee-grpc/coffee-grpc-opentracing-impl/src/main/java/hu/icellmobilsoft/coffee/grpc/opentracing/impl/server/OpenTraceServerInterceptor.java
- coffee-grpc/coffee-grpc-server-extension/pom.xml
- coffee-grpc/coffee-grpc-server-extension/src/main/java/hu/icellmobilsoft/coffee/grpc/server/GrpcServerManager.java
- coffee-grpc/coffee-grpc-traces-api/pom.xml
- coffee-grpc/coffee-grpc-traces-api/src/main/java/hu/icellmobilsoft/coffee/grpc/traces/api/ClientTracesInterceptorQualifier.java
- coffee-grpc/coffee-grpc-traces-api/src/main/java/hu/icellmobilsoft/coffee/grpc/traces/api/ITracesInterceptor.java
- coffee-grpc/coffee-grpc-traces-api/src/main/java/hu/icellmobilsoft/coffee/grpc/traces/api/ServerTracesInterceptorQualifier.java
- coffee-grpc/pom.xml
- coffee-module/coffee-module-mp/coffee-module-mp-opentracing/pom.xml
- coffee-module/coffee-module-mp/coffee-module-mp-opentracing/src/main/java/hu/icellmobilsoft/coffee/module/mp/opentracing/extension/OpenTraceInterceptor.java
- docs/common/core/coffee-grpc.adoc
- docs/common/module/coffee-module-mp-opentracing.adoc
- docs/migration/migration1130to1140.adoc
> #425 GRPC opentracing modul

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/sql/batch/BatchService.java
- docs/en/migration/migration200to210.adoc
- docs/hu/migration/migration200to210.adoc
- batchInsertNative
- batchUpdateNative
- migracios leiras
> #432 BatchService-vegye-figyelembe-insertable-updateable-flag-eket-master

- coffee-bom/pom.xml
- docs/migration/migration1130to1140.adoc
> #489 Bump guava 30.1.1 -> 32.1.1 v1

- coffee-bom/pom.xml
- docs/en/migration/migration200to210.adoc
- docs/hu/migration/migration200to210.adoc
> #488 Bump guava 31.1 -> 32.1.1

- coffee-bom/pom.xml
- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/health/constants/HealthConstant.java
- coffee-jpa/pom.xml
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealth.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthConstant.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthResourceConfig.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabasePoolHealth.java
- coffee-module/coffee-module-etcd/pom.xml
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/health/EtcdHealth.java
- coffee-module/coffee-module-redis/pom.xml
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/health/RedisHealth.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/health/HealthUtil.java
- docs/en/common/core/coffee-jpa.adoc
- docs/en/common/module/coffee-module-etcd.adoc
- docs/en/common/module/coffee-module-redis.adoc
- docs/en/migration/migration210to220.adoc
- docs/hu/common/core/coffee-jpa.adoc
- docs/hu/common/module/coffee-module-etcd.adoc
- docs/hu/common/module/coffee-module-redis.adoc
- docs/hu/migration/migration210to220.adoc
-jpa, redis, etcd health support
> #465 mp-health-support

- coffee-module/coffee-module-redis/pom.xml
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/metrics/IJedisMetricsHandler.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/metrics/JedisMetricsConstants.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/metrics/JedisMetricsHandler.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/producer/JedisConnectionProducer.java
- coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/CustomJedisMetricsHandler.java
- coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/CustomMetricsHandlerTest.java
- coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/JedisMetricsHandlerTest.java
- coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/JedisPoolTest.java
- coffee-module/coffee-module-redis/src/test/java/hu/icellmobilsoft/coffee/module/redis/config/RedisConfigTest.java
- docs/en/common/module/coffee-module-redis.adoc
- docs/en/migration/migration210to220.adoc
- docs/hu/common/module/coffee-module-redis.adoc
- docs/hu/migration/migration210to220.adoc
> #453 Jedis metrics

- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/ClassFieldsAndMethodsCache.java
- docs/en/migration/migration210to220.adoc
- docs/hu/migration/migration210to220.adoc
- ClassFieldsAndMethodsCache ConcurrentModificationException fix
> #525 ConcurrentModificationException

- coffee-bom/pom.xml
- coffee-cdi/src/main/java/hu/icellmobilsoft/coffee/cdi/health/constants/HealthConstant.java
- coffee-jpa/pom.xml
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealth.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthConstant.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthResourceConfig.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabasePoolHealth.java
- coffee-module/coffee-module-etcd/pom.xml
- coffee-module/coffee-module-etcd/src/main/java/hu/icellmobilsoft/coffee/module/etcd/health/EtcdHealth.java
- coffee-module/coffee-module-redis/pom.xml
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/health/RedisHealth.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/health/HealthUtil.java
- docs/common/core/coffee-jpa.adoc
- docs/common/module/coffee-module-etcd.adoc
- docs/common/module/coffee-module-redis.adoc
- docs/migration/migration1140to1150.adoc
-jpa, redis, etcd health support
> #521 mp-health-support

- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealth.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthConstant.java
- coffee-jpa/src/main/java/hu/icellmobilsoft/coffee/jpa/health/DatabaseHealthResourceConfig.java
- coffee-module/coffee-module-redis/src/main/java/hu/icellmobilsoft/coffee/module/redis/health/RedisHealth.java
- docs/common/core/coffee-jpa.adoc
> #530 health ds url

- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/stream/RequestLoggerInputStream.java
> #434 RequestResponseLogger memory tuning V2

- coffee-module/coffee-module-csv/pom.xml
- coffee-module/coffee-module-csv/src/main/java/hu/icellmobilsoft/coffee/module/csv/strategy/HeaderColumnNameWithPositionMappingStrategy.java
- coffee-module/coffee-module-csv/src/test/java/hu/icellmobilsoft/coffee/module/csv/LocalizedCsvUtilTest.java
- pom.xml
> #555 bump parent pom to 1.4.0

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/bootstrap/ConsumerLifeCycleManager.java
- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/consumer/RedisStreamConsumerExecutor.java
- docs/en/common/module/coffee-module-redisstream.adoc
- docs/en/migration/migration240to250.adoc
- docs/hu/common/module/coffee-module-redisstream.adoc
- docs/hu/migration/migration240to250.adoc
support consumer graceful shutdown
> #562 consumer graceful shutdown

- docs/en/migration/migration240to250.adoc
- docs/hu/migration/migration240to250.adoc
- pom.xml
> #587 - test classes were excluded from indexing

- docs/en/migration/migration240to250.adoc
- docs/hu/migration/migration240to250.adoc
> #577 micrometer support migration doc fix

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/log/optimized/BaseRestLogger.java
- coffee-tool/src/main/java/hu/icellmobilsoft/coffee/tool/utils/stream/ResponseEntityCollectorOutputStream.java
- coffee-tool/src/test/java/hu/icellmobilsoft/coffee/tool/utils/stream/ResponseEntityCollectorOutputStreamTest.java
- docs/en/migration/migration240to250.adoc
- docs/hu/migration/migration240to250.adoc
> #592 collect response entity as byte

- docs/en/migration/migration250to260.adoc
- docs/hu/migration/migration250to260.adoc
- Updated the migration documents with hibernate changes
> #584 - bump hibernate core to 6.2.13.Final

- coffee-deltaspike/coffee-deltaspike-data/src/main/java/org/apache/deltaspike/data/api/Modifying.java
> #597 removed Deprecated from Modifying

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/utils/XsdHelper.java
- docs/en/migration/migration250to260.adoc
- docs/hu/migration/migration250to260.adoc
- new methods for clearing cache
> #625 XsdHelper improve

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/reader/EmptyRequestVersionReader.java
- docs/en/migration/migration250to260.adoc
- docs/hu/migration/migration250to260.adoc
> #632 EmptyRequestVersionReader_dependent

- coffee-model/coffee-model-base/src/main/java/hu/icellmobilsoft/coffee/model/base/javatime/listener/TimestampsProvider.java
- coffee-model/coffee-model-base/src/test/java/hu/icellmobilsoft/coffee/model/base/GetterAnnotatedEntity.java
- coffee-model/coffee-model-base/src/test/java/hu/icellmobilsoft/coffee/model/base/javatime/TimestampsProviderTest.java
- docs/en/common/coffee-model.adoc
- docs/en/migration/migration260to270.adoc
- docs/hu/common/coffee-model.adoc
- docs/hu/migration/migration260to270.adoc
> 648 -  TimestampsProvider ZoneId ENV configuration 

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/catalog/CatalogProducer.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/JaxbTool.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/utils/IXsdHelper.java
- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/utils/XsdHelper.java
- docs/en/common/core/coffee-rest.adoc
- docs/en/migration/migration270to280.adoc
- docs/hu/common/core/coffee-rest.adoc
- docs/hu/migration/migration270to280.adoc
* a catalogproducert kiegeszitettem, hogy tudjon kezelni tobb xml-t is. (belefutottam a szuksegessegebe)
* soap envelope eseten szukseges, hogy tobb osztaly is bekerulhessen a jaxbcontextbe, mert az envelope.xsd egy Any elementet definial.
> #663 multiple catalog file

- coffee-rest/src/main/java/hu/icellmobilsoft/coffee/rest/validation/xml/JaxbTool.java
- docs/en/migration/migration270to280.adoc
i didnt add extra doc because this bug came from the previous modification in this milestone which is documented
> #667 jaxbtool casting issue fix

- .github/workflows/compile_maven.yml
- .github/workflows/docs.yml
- .github/workflows/manual_release.yml
- .github/workflows/maven-deploy.yml
- README.adoc
- docs/en/migration/migration290to2100.adoc
- docs/en/project-description.adoc
- docs/hu/migration/migration290to2100.adoc
- docs/hu/project-description.adoc
- Java11 support remove
- default java version set to 17
> #712 Java11 support remove

- coffee-module/coffee-module-redisstream/src/main/java/hu/icellmobilsoft/coffee/module/redisstream/publisher/RedisStreamPublisher.java
- docs/en/common/module/coffee-module-redisstream.adoc
- docs/en/migration/migration290to2100.adoc
- docs/hu/common/module/coffee-module-redisstream.adoc
- docs/hu/migration/migration290to2100.adoc
> #691 RedisStreamPublisher pipelined publish

- docs/en/migration/migration270to280.adoc
- docs/hu/migration/migration270to280.adoc
> #662 batchservice separation frappee links

- coffee-bom/coffee-bom-project/pom.xml
- coffee-quarkus-extensions/coffee-deltaspike-data-extension-parent/pom.xml
- coffee-quarkus-extensions/coffee-module-etcd-extension-parent/coffee-module-etcd-extension-deployment/pom.xml
- coffee-quarkus-extensions/coffee-module-etcd-extension-parent/coffee-module-etcd-extension-deployment/src/main/java/hu/icellmobilsoft/coffee/quarkus/extension/module/etcd/deployment/EtcdReflectionProcessor.java
- coffee-quarkus-extensions/coffee-module-etcd-extension-parent/coffee-module-etcd-extension/pom.xml
- coffee-quarkus-extensions/coffee-module-etcd-extension-parent/coffee-module-etcd-extension/src/main/resources/META-INF/quarkus-extension.yml
- coffee-quarkus-extensions/coffee-module-etcd-extension-parent/pom.xml
- coffee-quarkus-extensions/coffee-module-mp-restclient-extension-parent/pom.xml
- coffee-quarkus-extensions/coffee-tool-extension-parent/coffee-tool-extension-deployment/pom.xml
- coffee-quarkus-extensions/coffee-tool-extension-parent/coffee-tool-extension-deployment/src/main/java/hu/icellmobilsoft/coffee/quarkus/extension/tool/deployment/ToolReflectionProcessor.java
- coffee-quarkus-extensions/coffee-tool-extension-parent/coffee-tool-extension/pom.xml
- coffee-quarkus-extensions/coffee-tool-extension-parent/coffee-tool-extension/src/main/resources/META-INF/quarkus-extension.yml
- coffee-quarkus-extensions/coffee-tool-extension-parent/pom.xml
- coffee-quarkus-extensions/pom.xml
- docs/en/common/coffee-quarkus-extensions.adoc
- docs/en/common/quarkus-extension/coffee-module-etcd-extension.adoc
- docs/en/common/quarkus-extension/coffee-tool-extension.adoc
- docs/en/migration/migration2100to2110.adoc
- docs/hu/common/coffee-quarkus-extensions.adoc
- docs/hu/common/quarkus-extension/coffee-module-etcd-extension.adoc
- docs/hu/common/quarkus-extension/coffee-tool-extension.adoc
- docs/hu/migration/migration2100to2110.adoc
> Quarkus native extensions
